# generate SBATCH scripts to run calibration and analyses on server
# usually much more efficient to run as 3000 separate jobs, each with one set, than to run 3000 sets in parallel using one script
# for calibration, generate 6 sets of 500 jobs to run at a time (due to usage limits)
# need to adjust country and date

dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617")
dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set1")
dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set2")
dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set3")
dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set4")
dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set5")
dir.create("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set6")

for (i in 1:500){
  sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set1/arg_ps",i,".sh"))
  cat('#!/bin/bash\n')
  cat('#SBATCH --nodes=1\n')
  cat('#SBATCH --time=0-6:00:00\n')
  cat(paste0('#SBATCH --job-name=arg_ps',i,'\n'))
  cat(paste0('#SBATCH --output=arg_ps',i,'.out','\n'))
  cat('#SBATCH --error=argtest.err\n')
  cat('#SBATCH -p normal\n')
  cat('#SBATCH -c 1\n')
  cat('#SBATCH --mem=1GB\n')
  cat('\n')
  cat('ml R/4.2.0\n')
  cat(paste0('Rscript ~/TBprisons/scripts/main_script_argentina_sherlock_240617.R ', i, '\n'))
  cat('\n')
  sink()
}
for (i in 501:1000){
  sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set2/arg_ps",i,".sh"))
  cat('#!/bin/bash\n')
  cat('#SBATCH --nodes=1\n')
  cat('#SBATCH --time=0-6:00:00\n')
  cat(paste0('#SBATCH --job-name=arg_ps',i,'\n'))
  cat(paste0('#SBATCH --output=arg_ps',i,'.out','\n'))
  cat('#SBATCH --error=argtest.err\n')
  cat('#SBATCH -p normal\n')
  cat('#SBATCH -c 1\n')
  cat('#SBATCH --mem=1GB\n')
  cat('\n')
  cat('ml R/4.2.0\n')
  cat(paste0('Rscript ~/TBprisons/scripts/main_script_argentina_sherlock_240617.R ', i, '\n'))
  cat('\n')
  sink()
}
for (i in 1001:1500){
  sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set3/arg_ps",i,".sh"))
  cat('#!/bin/bash\n')
  cat('#SBATCH --nodes=1\n')
  cat('#SBATCH --time=0-6:00:00\n')
  cat(paste0('#SBATCH --job-name=arg_ps',i,'\n'))
  cat(paste0('#SBATCH --output=arg_ps',i,'.out','\n'))
  cat('#SBATCH --error=argtest.err\n')
  cat('#SBATCH -p normal\n')
  cat('#SBATCH -c 1\n')
  cat('#SBATCH --mem=1GB\n')
  cat('\n')
  cat('ml R/4.2.0\n')
  cat(paste0('Rscript ~/TBprisons/scripts/main_script_argentina_sherlock_240617.R ', i, '\n'))
  cat('\n')
  sink()
}
for (i in 1501:2000){
  sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set4/arg_ps",i,".sh"))
  cat('#!/bin/bash\n')
  cat('#SBATCH --nodes=1\n')
  cat('#SBATCH --time=0-6:00:00\n')
  cat(paste0('#SBATCH --job-name=arg_ps',i,'\n'))
  cat(paste0('#SBATCH --output=arg_ps',i,'.out','\n'))
  cat('#SBATCH --error=argtest.err\n')
  cat('#SBATCH -p normal\n')
  cat('#SBATCH -c 1\n')
  cat('#SBATCH --mem=1GB\n')
  cat('\n')
  cat('ml R/4.2.0\n')
  cat(paste0('Rscript ~/TBprisons/scripts/main_script_argentina_sherlock_240617.R ', i, '\n'))
  cat('\n')
  sink()
}
for (i in 2001:2500){
  sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set5/arg_ps",i,".sh"))
  cat('#!/bin/bash\n')
  cat('#SBATCH --nodes=1\n')
  cat('#SBATCH --time=0-6:00:00\n')
  cat(paste0('#SBATCH --job-name=arg_ps',i,'\n'))
  cat(paste0('#SBATCH --output=arg_ps',i,'.out','\n'))
  cat('#SBATCH --error=argtest.err\n')
  cat('#SBATCH -p normal\n')
  cat('#SBATCH -c 1\n')
  cat('#SBATCH --mem=1GB\n')
  cat('\n')
  cat('ml R/4.2.0\n')
  cat(paste0('Rscript ~/TBprisons/scripts/main_script_argentina_sherlock_240617.R ', i, '\n'))
  cat('\n')
  sink()
}
for (i in 2501:3000){
  sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/argentina_240617/set6/arg_ps",i,".sh"))
  cat('#!/bin/bash\n')
  cat('#SBATCH --nodes=1\n')
  cat('#SBATCH --time=0-6:00:00\n')
  cat(paste0('#SBATCH --job-name=arg_ps',i,'\n'))
  cat(paste0('#SBATCH --output=arg_ps',i,'.out','\n'))
  cat('#SBATCH --error=argtest.err\n')
  cat('#SBATCH -p normal\n')
  cat('#SBATCH -c 1\n')
  cat('#SBATCH --mem=1GB\n')
  cat('\n')
  cat('ml R/4.2.0\n')
  cat(paste0('Rscript ~/TBprisons/scripts/main_script_argentina_sherlock_240617.R ', i, '\n'))
  cat('\n')
  sink()
}

# scripts for future projections - need to adjust country and date
sink(paste0("~/Library/CloudStorage/Box-Box/yiranliu/STANFORD/TBprisons/scripts/sherlock/future_projections/per_fut_3.sh"))
cat('#!/bin/bash\n')
cat('#SBATCH --nodes=1\n')
cat('#SBATCH --time=1-00:00:00\n')
cat('#SBATCH --job-name=per_fut_3\n')
cat('#SBATCH --output=per_fut_3.out\n')
cat('#SBATCH --error=per_fut_3.err\n')
cat('#SBATCH -p normal\n')
cat('#SBATCH -c 1\n')
cat('#SBATCH --mem=5GB\n')
cat('\n')
cat('ml R/4.2.0\n')
cat('\n')
cat('Rscript ~/TBprisons/scripts/future_projections_sherlock_240703.R 2001 3000 240612 Peru')
sink()
